"use client";

import { useEffect, useMemo, useState } from "react";
import type { FlowLane, FlowLaneSummary, FlowReceipt } from "@/lib/flow-receipt";
import type { projectFlowAudit } from "@/lib/flow-projection";

type Audit = ReturnType<typeof projectFlowAudit>;
type Detail = { title: string; status: string; lines: string[]; receipts: FlowReceipt[]; items: Array<{ kind: string; text: string }> };
const STATUS: Record<string, { en: string; zh: string }> = { not_observed: { en: "Not observed", zh: "未观测" }, observed: { en: "Observed", zh: "已观测" }, delivered: { en: "Delivered", zh: "已送达" }, verified: { en: "Verified", zh: "已验证" }, candidate_returned: { en: "Candidates returned", zh: "已返回候选" }, unknown: { en: "Unknown", zh: "未知" } };
const LANE: Record<FlowLane, { en: string; zh: string; accent: string; icon: string }> = { ingress: { en: "Prompt & Host Ingress", zh: "Prompt 与宿主入口", accent: "blue", icon: "01" }, guidance: { en: "Guidance & Navigation", zh: "说明与导航", accent: "violet", icon: "02" }, user_memory: { en: "User Memory", zh: "用户记忆", accent: "teal", icon: "A" }, agent_process: { en: "Agent Process Memory", zh: "智能体过程记忆", accent: "amber", icon: "B" }, external_rag: { en: "External RAG", zh: "外部 RAG", accent: "cyan", icon: "C" }, model_context: { en: "Models & Context", zh: "模型与上下文", accent: "indigo", icon: "04" }, execution_writeback: { en: "Execution & Writeback", zh: "执行与写回", accent: "emerald", icon: "03" } };
const BRANCHES: Record<string, { en: string; zh: string }[]> = { user_memory: [{ en: "Recall", zh: "Recall" }, { en: "Research", zh: "Research" }, { en: "Scenario Summary", zh: "情景摘要" }, { en: "Read Source", zh: "原文回读" }], agent_process: [{ en: "Observe trajectory", zh: "观察轨迹" }, { en: "Process retrieval", zh: "过程检索" }, { en: "Compatibility gate", zh: "兼容性门控" }, { en: "Hint / Recommend / Scaffold / Guard", zh: "提示 / 建议 / 脚手架 / 防护" }], external_rag: [{ en: "Lexical", zh: "词法检索" }, { en: "Vector", zh: "向量检索" }, { en: "Fusion / RRF", zh: "融合 / RRF" }, { en: "Rerank", zh: "Rerank" }, { en: "JEV review", zh: "JEV 审查" }] };
const itemText = (item: { text?: string; text_preview?: string; title?: string; id?: string }) => item.text || item.text_preview || item.title || item.id || "—";

export function FlowLanesOverview({ promptId, english, audit }: { promptId?: string | null; english: boolean; audit?: Audit | null }) {
  const [apiLanes, setApiLanes] = useState<FlowLaneSummary[]>([]); const [sourceScope, setSourceScope] = useState("no_bound_process_receipt"); const [selected, setSelected] = useState<Detail | null>(null);
  useEffect(() => { if (!promptId) { setApiLanes([]); setSourceScope("no_prompt"); return; } const controller = new AbortController(); fetch(`/api/evolving-profile/flow/${encodeURIComponent(promptId)}`, { cache: "no-store", signal: controller.signal }).then((response) => response.ok ? response.json() : null).then((payload) => { setApiLanes(payload?.lanes ?? []); setSourceScope(payload?.source_scope ?? "unknown"); }).catch((error) => { if (error?.name !== "AbortError") { setApiLanes([]); setSourceScope("unavailable"); } }); return () => controller.abort(); }, [promptId]);
  const apiByLane = useMemo(() => new Map(apiLanes.map((lane) => [lane.lane, lane])), [apiLanes]); const text = (lane: FlowLane) => LANE[lane][english ? "en" : "zh"]; const state = (status?: string) => STATUS[status ?? "not_observed"]?.[english ? "en" : "zh"] ?? (english ? "Unknown" : "未知"); const auditMemory = audit?.history;
  const preferenceCandidates = Math.max(audit?.guidance.candidateCount ?? 0, audit?.guidance.count ?? 0); const preferenceReturned = audit?.guidance.count ?? 0; const historyCandidates = auditMemory && (auditMemory.calls ?? 0) > 0 ? (auditMemory.metrics.candidates ?? 0) : 0; const historyReturned = auditMemory && (auditMemory.calls ?? 0) > 0 ? (auditMemory.metrics.returned ?? 0) : 0;
  const isSyncing = Boolean(promptId && !audit);
  const effective = (lane: FlowLane): FlowLaneSummary => { const base = apiByLane.get(lane) ?? { lane, status: "not_observed", receipts: [], counts: { candidates: 0, returned: 0, delivered: 0, tokens: 0 } }; if (lane === "user_memory") { const historyCalled = (auditMemory?.calls ?? 0) > 0; const returned = preferenceReturned + historyReturned; const status = historyReturned > 0 ? "candidate_returned" : preferenceReturned > 0 ? "delivered" : historyCalled ? "observed" : "not_observed"; return { ...base, status, counts: { candidates: preferenceCandidates + historyCandidates, returned, delivered: preferenceReturned + (auditMemory?.delivered ?? 0), tokens: 0 } }; } if (lane === "guidance" && audit) return { ...base, status: audit.guidance.count ? "delivered" : "not_observed", counts: { candidates: preferenceCandidates, returned: audit.guidance.count, delivered: audit.guidance.count, tokens: 0 } }; if (lane === "ingress" && audit?.entry.instruction) return { ...base, status: "observed" }; if (lane === "model_context" && audit?.map.l0.status === "observed") return { ...base, status: "delivered" }; return base; };
  const deliveryDisplay = (lane: FlowLane, data: FlowLaneSummary) => lane === "user_memory" && auditMemory && (auditMemory.calls ?? 0) > 0 && auditMemory.delivered == null ? (english ? "unmeasured" : "未测量") : String(data.counts.delivered);
  const memoryMetricLabel = () => english ? `Preferences ${preferenceCandidates} · History ${historyCandidates} · Delivered ${auditMemory && (auditMemory.calls ?? 0) > 0 && auditMemory.delivered == null ? "unmeasured" : preferenceReturned + (auditMemory?.delivered ?? 0)}` : `偏好 ${preferenceCandidates} · 历史 ${historyCandidates} · 送达 ${auditMemory && (auditMemory.calls ?? 0) > 0 && auditMemory.delivered == null ? "未测量" : preferenceReturned + (auditMemory?.delivered ?? 0)}`;
  const openDetail = (lane: FlowLane, branch?: string) => { const data = effective(lane); const scope = lane === "agent_process" && sourceScope === "no_bound_process_receipt" ? (english ? "No Prompt-bound process receipt" : "没有绑定到本 Prompt 的过程回执") : lane === "user_memory" && audit ? (english ? "Prompt audit + history route projection" : "Prompt 审计与历史路线投影") : sourceScope; const lines = [`${english ? "Evidence scope" : "证据范围"}: ${scope}`, `${english ? "Candidates" : "候选"}: ${data.counts.candidates} · ${english ? "Returned" : "返回"}: ${data.counts.returned} · ${english ? "Delivered" : "送达"}: ${deliveryDisplay(lane, data)}`]; const items: Array<{ kind: string; text: string }> = []; if (lane === "user_memory") { lines.push(`${english ? "Preference summaries" : "偏好摘要"}: ${preferenceCandidates} · ${english ? "Preference returned" : "偏好已送达"}: ${preferenceReturned}`); lines.push(`${english ? "History candidates" : "历史候选"}: ${historyCandidates} · ${english ? "History returned" : "历史返回"}: ${historyReturned}`); if (audit) items.push(...audit.guidance.items.map((item) => ({ kind: english ? "Preference" : "偏好", text: itemText(item) }))); if (auditMemory) items.push(...auditMemory.items.map((item) => ({ kind: english ? "Recall / Research" : "Recall / Research", text: itemText(item) }))); } else if (lane === "guidance" && audit) { lines.push(`${english ? "Preference summaries" : "偏好摘要"}: ${audit.guidance.count} · ${english ? "Deferred" : "待补读"}: ${audit.guidance.deferred}`); items.push(...audit.guidance.items.map((item) => ({ kind: english ? "Preference" : "偏好", text: itemText(item) }))); } if (lane === "user_memory" && auditMemory) lines.push(`${english ? "History route" : "历史路线"}: ${auditMemory.value || "not_observed"} · ${english ? "Calls" : "调用"}: ${auditMemory.calls}`); if (!data.receipts.length && lane === "agent_process") lines.push(english ? "Global process records may exist, but this prompt has no bound process receipt; no timestamp guessing is performed." : "全局过程记录可能存在，但本 Prompt 没有绑定过程回执；系统不会按时间猜测归属。"); if (branch) lines.push(`${english ? "Route node" : "路线节点"}: ${branch}`); setSelected({ title: branch ?? text(lane), status: state(data.status), lines, receipts: data.receipts, items }); };
  const laneCard = (lane: FlowLane, subtitle: string) => { const data = effective(lane); const meta = LANE[lane]; return <button type="button" key={lane} onClick={() => openDetail(lane)} className={`topology-lane topology-${meta.accent}`}><div className="topology-lane-badge">{meta.icon}</div><div className="topology-lane-head"><span className="topology-lane-title">{text(lane)}</span><span className="topology-status">{isSyncing ? (english ? "Syncing" : "同步中") : state(data.status)}</span></div><div className="topology-lane-subtitle">{subtitle}</div><div className="topology-lane-metrics">{isSyncing ? (english ? "Loading receipt…" : "正在同步回执…") : lane === "user_memory" ? memoryMetricLabel() : `${english ? "Candidates" : "候选"} ${data.counts.candidates} · ${english ? "Delivered" : "送达"} ${deliveryDisplay(lane, data)}`}</div></button>; };
  const branchCard = (lane: FlowLane, item: { en: string; zh: string }) => <button type="button" key={item.en} className="topology-branch-node" onClick={() => openDetail(lane, english ? item.en : item.zh)}>{english ? item.en : item.zh}</button>;
  return <><section className="topology-shell"><div className="topology-heading"><div><div className="topology-kicker">{english ? "EXECUTION TOPOLOGY" : "执行拓扑"}</div><h2>{english ? "Full Chain" : "全链路"}</h2><p>{english ? "Serial spine, parallel lanes, explicit forks, merges, and writeback." : "串行主干、并行泳道、显式分支、汇聚和写回。"}</p></div><span className="topology-phase">{english ? "Live receipt projection" : "实时回执投影"}</span></div>
    <div className="topology-serial-panel"><div className="topology-section-label"><b>1</b><strong>{english ? "SERIAL" : "串行"}</strong><span>{english ? "Prompt → Context → Execution" : "Prompt → 上下文 → 执行"}</span></div><div className="topology-serial"><NodeButton title={english ? "Prompt Ingress" : "Prompt 入口"} detail={english ? "User request received" : "收到用户请求"} onClick={() => openDetail("ingress")} /><i>→</i><NodeButton title={english ? "Host / Hook Binding" : "宿主 / Hook 绑定"} detail={english ? "Bind tools, skills, environment" : "绑定工具、Skill、环境"} onClick={() => openDetail("ingress", english ? "Host / Hook Binding" : "宿主 / Hook 绑定")} /><i>→</i><NodeButton title={english ? "Task Contract" : "任务契约"} detail={english ? "Parse, plan, authorize" : "解析、规划、授权"} onClick={() => openDetail("guidance", english ? "Task Contract" : "任务契约")} /><b className="topology-fork">{english ? "FORK" : "分支"}</b><NodeButton title={english ? "Context Assembly" : "上下文组装"} detail={english ? "Unify memory and sources" : "汇总记忆与来源"} onClick={() => openDetail("model_context")} /><i>→</i><NodeButton title={english ? "Agent Execution" : "Agent 执行"} detail={english ? "Reason, act, generate" : "推理、行动、生成"} onClick={() => openDetail("model_context", english ? "Agent Execution" : "Agent 执行")} /></div></div>
    <div className="topology-parallel-panel"><div className="topology-section-label"><b>2</b><strong>{english ? "PARALLEL" : "并行"}</strong><span>{english ? "Memory & Knowledge Retrieval" : "记忆与知识检索"}</span></div>
      <div className="topology-lane-row">{laneCard("user_memory", english ? "Preferences, history, long-term context" : "偏好、历史、长期情境")}<div className="topology-branch-flow"><span className="topology-flow-tag">FORK</span><div className="topology-branch-grid">{BRANCHES.user_memory.map((item) => branchCard("user_memory", item))}</div><span className="topology-flow-tag">MERGE</span></div><button type="button" className="topology-packet" onClick={() => openDetail("user_memory", english ? "User Memory Packet" : "用户记忆包")}>{english ? "User Memory Packet" : "用户记忆包"}<small>{english ? "Curated user context" : "整理后的用户上下文"}</small></button></div>
      <div className="topology-lane-row">{laneCard("agent_process", english ? "Trajectory, process retrieval, intervention" : "轨迹、过程检索、干预")}<div className="topology-branch-flow"><span className="topology-flow-tag">GATE</span><div className="topology-branch-grid">{BRANCHES.agent_process.map((item) => branchCard("agent_process", item))}</div><span className="topology-flow-tag">PACKET</span></div><button type="button" className="topology-packet" onClick={() => openDetail("agent_process", english ? "Process Memory Packet" : "过程记忆包")}>{english ? "Process Memory Packet" : "过程记忆包"}<small>{english ? "Execution guidance" : "执行指导"}</small></button></div>
      <div className="topology-lane-row">{laneCard("external_rag", english ? "External documents and knowledge" : "外部文档与知识")}<div className="topology-branch-flow"><span className="topology-flow-tag">FORK</span><div className="topology-branch-grid">{BRANCHES.external_rag.map((item) => branchCard("external_rag", item))}</div><span className="topology-flow-tag">MERGE</span></div><button type="button" className="topology-packet" onClick={() => openDetail("external_rag", english ? "RAG Packet" : "RAG 知识包")}>{english ? "RAG Packet" : "RAG 知识包"}<small>{english ? "Grounded knowledge" : "有依据的外部知识"}</small></button></div>
    </div><div className="topology-merge-bar">{english ? "MERGE → Context Packet → Agent" : "汇聚 → 上下文包 → Agent"}</div>
    <div className="topology-writeback-panel"><div className="topology-section-label"><b>3</b><strong>{english ? "SERIAL" : "串行"}</strong><span>{english ? "Execution Outputs & Writeback" : "执行输出与写回"}</span></div><div className="topology-writeback-row"><NodeButton title={english ? "User Writeback" : "用户记忆写回"} detail={english ? "Update user memory" : "更新用户记忆"} onClick={() => openDetail("execution_writeback")} /><i>→</i><NodeButton title={english ? "Agent Writeback" : "智能体记忆写回"} detail={english ? "Update process memory" : "更新过程记忆"} onClick={() => openDetail("execution_writeback", english ? "Agent Writeback" : "智能体记忆写回")} /><i>→</i><NodeButton title={english ? "Audit Receipt" : "审计回执"} detail={english ? "Trace, citation, policy" : "轨迹、引用、策略"} onClick={() => openDetail("execution_writeback", english ? "Audit Receipt" : "审计回执")} /><i>→</i><NodeButton title={english ? "Final Response" : "最终回答"} detail={english ? "Deliver to user" : "交付给用户"} onClick={() => openDetail("execution_writeback", english ? "Final Response" : "最终回答")} /></div></div></section>
    {selected && <div className="topology-modal" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><div className="topology-modal-card" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => setSelected(null)} className="topology-modal-close" aria-label={english ? "Close" : "关闭"}>×</button><div className="topology-kicker">{english ? "RECEIPT DETAILS" : "回执详情"}</div><h3>{selected.title}</h3><div className="topology-detail-status">{selected.status}</div><div className="topology-detail-lines">{selected.lines.map((line) => <p key={line}>{line}</p>)}</div>{selected.items.length > 0 && <div className="topology-receipt-items"><h4>{english ? "Items delivered to the Agent" : "实际送给 Agent 的条目"}</h4>{selected.items.map((item, index) => <div className="topology-receipt-item" key={`${item.kind}-${index}`}><span>{item.kind}</span><p>{item.text}</p></div>)}</div>}{selected.receipts.length ? <div className="topology-receipts">{selected.receipts.map((receipt) => <article key={receipt.trace_id}><b>{receipt.stage}</b><span>{receipt.status}</span><p>{receipt.summary}</p><small>{receipt.trace_id}</small></article>)}</div> : !selected.items.length && <div className="topology-empty-receipt">{english ? "No bound receipt was returned for this node in the selected turn. The status above is intentionally not inferred from availability or global records." : "当前选中回合没有返回绑定到此节点的回执。上面的状态不会根据可用能力或全局记录臆测。"}</div>}</div></div>}
  </>;
}
function NodeButton({ title, detail, onClick }: { title: string; detail: string; onClick: () => void }) { return <button type="button" className="topology-node" onClick={onClick}><strong>{title}</strong><small>{detail}</small></button>; }
