// Native short labels. Longer legacy explanations have an explicit English fallback.
export const RELEASE_UI_LOCALIZED: Record<string,Record<string,string>> = {
  "de": {
    "localModelDirectory": "Lokales Modellverzeichnis",
    "dimensions": "Vektordimensionen",
    "device": "Gerät",
    "embeddingProfiles": "Embedding-Profile",
    "rerankerProfiles": "Rerank-Profile",
    "copy": "Kopieren",
    "enable": "Aktivieren",
    "disable": "Aus",
    "source": "Quelle",
    "hostedUrl": "API-URL",
    "fixedUrl": "Verwaltete Dienst-URL",
    "fixedModel": "Verwaltetes Modell",
    "previousConfig": "Vorherige Konfiguration",
    "discovered": "Entdeckt",
    "modelId": "Modell-ID",
    "providerName": "Anbietername",
    "primaryProvider": "Primärer Anbieter",
    "remove": "Entfernen",
    "unconfigured": "Nicht konfiguriert",
    "scenarioHint": "Sitzungs- und Projektzusammenfassungen, Prüfung und Graphabdeckung.",
    "pendingReview": "Prüfung ausstehend:",
    "qualityStatus": "Qualitätsstatus:",
    "graphNodes": "Graphknoten",
    "relationEdges": "· Beziehungskanten",
    "timelineSuffix": "· Zeitachse",
    "tier": "Ebene",
    "overview": "Übersicht",
    "standardSummary": "Standardzusammenfassung",
    "fullSummary": "Ausführliche Zusammenfassung",
    "nodeName": "Knotenname",
    "scopeReview": "Bereichsprüfung",
    "sourceCount": "Quellenanzahl",
    "sourceLocator": "Quellenverweis",
    "none": "Keine",
    "boundary": "Geltungsgrenze",
    "sampleNodes": "Graph-Stichprobe",
    "linkedBank": "Verknüpfte Bank-Datensätze",
    "scenarioVisualization": "Szenariovisualisierung",
    "constellation": "Konstellation",
    "graph": "Graph",
    "table": "Tabelle",
    "timeline": "Zeitachse",
    "relationship": "Beziehung",
    "sourceNode": "Quellknoten",
    "targetNode": "Zielknoten",
    "unknownTime": "Zeit unbekannt",
    "scenarioDetails": "Szenariodetails",
    "stable": "Stabil",
    "verified": "Verifiziert",
    "candidate": "Kandidat",
    "unknown": "Unbekannt",
    "watch": "Aufmerksamkeit erforderlich",
    "revalidation": "Erneute Prüfung ausstehend",
    "deprecated": "Veraltet",
    "configured": "Konfiguriert"
  },
  "es": {
    "localModelDirectory": "Directorio del modelo local",
    "dimensions": "Dimensiones del vector",
    "device": "Dispositivo",
    "embeddingProfiles": "Perfiles de embedding",
    "rerankerProfiles": "Perfiles de reranking",
    "copy": "Copiar",
    "enable": "Activar",
    "disable": "Desactivado",
    "source": "Fuente",
    "hostedUrl": "URL de la API",
    "fixedUrl": "URL del servicio administrado",
    "fixedModel": "Modelo administrado",
    "previousConfig": "Configuración anterior",
    "discovered": "Descubierto",
    "modelId": "ID del modelo",
    "providerName": "Nombre del proveedor",
    "primaryProvider": "Proveedor principal",
    "remove": "Eliminar",
    "unconfigured": "Sin configurar",
    "scenarioHint": "Resúmenes de sesiones y proyectos, revisión y cobertura del grafo.",
    "pendingReview": "Revisión pendiente:",
    "qualityStatus": "Estado de calidad:",
    "graphNodes": "Nodos del grafo",
    "relationEdges": "· relaciones",
    "timelineSuffix": "· cronología",
    "tier": "Nivel",
    "overview": "Resumen",
    "standardSummary": "Resumen estándar",
    "fullSummary": "Resumen detallado",
    "nodeName": "Nombre del nodo",
    "scopeReview": "Revisión del alcance",
    "sourceCount": "Número de fuentes",
    "sourceLocator": "Localizador de la fuente",
    "none": "Ninguno",
    "boundary": "Límite del alcance",
    "sampleNodes": "Nodos de muestra",
    "linkedBank": "Registros Bank vinculados",
    "scenarioVisualization": "Visualización de escenarios",
    "constellation": "Constelación",
    "graph": "Grafo",
    "table": "Tabla",
    "timeline": "Cronología",
    "relationship": "Relación",
    "sourceNode": "Nodo de origen",
    "targetNode": "Nodo de destino",
    "unknownTime": "Hora desconocida",
    "scenarioDetails": "Detalles del escenario",
    "stable": "Estable",
    "verified": "Verificado",
    "candidate": "Candidato",
    "unknown": "Desconocido",
    "watch": "Requiere atención",
    "revalidation": "Revalidación pendiente",
    "deprecated": "Obsoleto",
    "configured": "Configurado"
  },
  "fr": {
    "localModelDirectory": "Répertoire du modèle local",
    "dimensions": "Dimensions du vecteur",
    "device": "Appareil",
    "embeddingProfiles": "Profils d’embedding",
    "rerankerProfiles": "Profils de reclassement",
    "copy": "Copier",
    "enable": "Activer",
    "disable": "Désactivé",
    "source": "Source",
    "hostedUrl": "URL de l’API",
    "fixedUrl": "URL du service géré",
    "fixedModel": "Modèle géré",
    "previousConfig": "Configuration précédente",
    "discovered": "Découvert",
    "modelId": "ID du modèle",
    "providerName": "Nom du fournisseur",
    "primaryProvider": "Fournisseur principal",
    "remove": "Supprimer",
    "unconfigured": "Non configuré",
    "scenarioHint": "Résumés des sessions et projets, révision et couverture du graphe.",
    "pendingReview": "Révision en attente :",
    "qualityStatus": "État de qualité :",
    "graphNodes": "Nœuds du graphe",
    "relationEdges": "· relations",
    "timelineSuffix": "· chronologie",
    "tier": "Niveau",
    "overview": "Vue d’ensemble",
    "standardSummary": "Résumé standard",
    "fullSummary": "Résumé détaillé",
    "nodeName": "Nom du nœud",
    "scopeReview": "Révision du périmètre",
    "sourceCount": "Nombre de sources",
    "sourceLocator": "Localisateur de source",
    "none": "Aucun",
    "boundary": "Limite du périmètre",
    "sampleNodes": "Échantillon de nœuds",
    "linkedBank": "Enregistrements Bank liés",
    "scenarioVisualization": "Visualisation des scénarios",
    "constellation": "Constellation",
    "graph": "Graphe",
    "table": "Tableau",
    "timeline": "Chronologie",
    "relationship": "Relation",
    "sourceNode": "Nœud source",
    "targetNode": "Nœud cible",
    "unknownTime": "Heure inconnue",
    "scenarioDetails": "Détails du scénario",
    "stable": "Stable",
    "verified": "Vérifié",
    "candidate": "Candidat",
    "unknown": "Inconnu",
    "watch": "Attention requise",
    "revalidation": "Revalidation en attente",
    "deprecated": "Obsolète",
    "configured": "Configuré"
  },
  "pt": {
    "localModelDirectory": "Diretório do modelo local",
    "dimensions": "Dimensões do vetor",
    "device": "Dispositivo",
    "embeddingProfiles": "Perfis de embedding",
    "rerankerProfiles": "Perfis de reclassificação",
    "copy": "Copiar",
    "enable": "Ativar",
    "disable": "Desativado",
    "source": "Fonte",
    "hostedUrl": "URL da API",
    "fixedUrl": "URL do serviço gerenciado",
    "fixedModel": "Modelo gerenciado",
    "previousConfig": "Configuração anterior",
    "discovered": "Descoberto",
    "modelId": "ID do modelo",
    "providerName": "Nome do provedor",
    "primaryProvider": "Provedor principal",
    "remove": "Remover",
    "unconfigured": "Não configurado",
    "scenarioHint": "Resumos de sessões e projetos, revisão e cobertura do grafo.",
    "pendingReview": "Revisão pendente:",
    "qualityStatus": "Estado de qualidade:",
    "graphNodes": "Nós do grafo",
    "relationEdges": "· relações",
    "timelineSuffix": "· linha do tempo",
    "tier": "Nível",
    "overview": "Visão geral",
    "standardSummary": "Resumo padrão",
    "fullSummary": "Resumo detalhado",
    "nodeName": "Nome do nó",
    "scopeReview": "Revisão de escopo",
    "sourceCount": "Número de fontes",
    "sourceLocator": "Localizador da fonte",
    "none": "Nenhum",
    "boundary": "Limite de escopo",
    "sampleNodes": "Nós de amostra",
    "linkedBank": "Registros Bank vinculados",
    "scenarioVisualization": "Visualização de cenários",
    "constellation": "Constelação",
    "graph": "Grafo",
    "table": "Tabela",
    "timeline": "Linha do tempo",
    "relationship": "Relação",
    "sourceNode": "Nó de origem",
    "targetNode": "Nó de destino",
    "unknownTime": "Horário desconhecido",
    "scenarioDetails": "Detalhes do cenário",
    "stable": "Estável",
    "verified": "Verificado",
    "candidate": "Candidato",
    "unknown": "Desconhecido",
    "watch": "Requer atenção",
    "revalidation": "Revalidação pendente",
    "deprecated": "Obsoleto",
    "configured": "Configurado"
  },
  "ja": {
    "localModelDirectory": "ローカルモデルのディレクトリ",
    "dimensions": "ベクトル次元",
    "device": "実行デバイス",
    "embeddingProfiles": "埋め込みプロファイル",
    "rerankerProfiles": "再ランキングプロファイル",
    "copy": "コピー",
    "enable": "有効にする",
    "disable": "オフ",
    "source": "ソース",
    "hostedUrl": "API URL",
    "fixedUrl": "管理されたサービス URL",
    "fixedModel": "管理されたモデル",
    "previousConfig": "以前の設定",
    "discovered": "検出済み",
    "modelId": "モデル ID",
    "providerName": "プロバイダー名",
    "primaryProvider": "主要プロバイダー",
    "remove": "削除",
    "unconfigured": "未設定",
    "scenarioHint": "セッションとプロジェクトの要約、レビュー状態、グラフの対象範囲。",
    "pendingReview": "レビュー待ち：",
    "qualityStatus": "品質状態：",
    "graphNodes": "グラフのノード",
    "relationEdges": "・関係エッジ",
    "timelineSuffix": "・タイムライン",
    "tier": "レベル",
    "overview": "概要",
    "standardSummary": "標準要約",
    "fullSummary": "詳細要約",
    "nodeName": "ノード名",
    "scopeReview": "範囲のレビュー",
    "sourceCount": "ソース数",
    "sourceLocator": "ソースの参照先",
    "none": "なし",
    "boundary": "対象範囲の境界",
    "sampleNodes": "サンプルノード",
    "linkedBank": "関連付けられた Bank レコード",
    "scenarioVisualization": "シナリオの可視化",
    "constellation": "星座",
    "graph": "グラフ",
    "table": "表",
    "timeline": "タイムライン",
    "relationship": "関係",
    "sourceNode": "参照元ノード",
    "targetNode": "参照先ノード",
    "unknownTime": "時刻不明",
    "scenarioDetails": "シナリオの詳細",
    "stable": "安定",
    "verified": "検証済み",
    "candidate": "候補",
    "unknown": "不明",
    "watch": "確認が必要",
    "revalidation": "再検証待ち",
    "deprecated": "非推奨",
    "configured": "設定済み"
  },
  "ko": {
    "localModelDirectory": "로컬 모델 디렉터리",
    "dimensions": "벡터 차원",
    "device": "실행 장치",
    "embeddingProfiles": "임베딩 프로필",
    "rerankerProfiles": "재순위화 프로필",
    "copy": "복사",
    "enable": "활성화",
    "disable": "끄기",
    "source": "출처",
    "hostedUrl": "API URL",
    "fixedUrl": "관리 서비스 URL",
    "fixedModel": "관리 모델",
    "previousConfig": "이전 설정",
    "discovered": "발견됨",
    "modelId": "모델 ID",
    "providerName": "제공자 이름",
    "primaryProvider": "기본 제공자",
    "remove": "제거",
    "unconfigured": "미설정",
    "scenarioHint": "세션 및 프로젝트 요약, 검토 상태와 그래프 범위.",
    "pendingReview": "검토 대기:",
    "qualityStatus": "품질 상태:",
    "graphNodes": "그래프 노드",
    "relationEdges": "· 관계",
    "timelineSuffix": "· 시간선",
    "tier": "단계",
    "overview": "개요",
    "standardSummary": "표준 요약",
    "fullSummary": "상세 요약",
    "nodeName": "노드 이름",
    "scopeReview": "범위 검토",
    "sourceCount": "출처 수",
    "sourceLocator": "출처 위치",
    "none": "없음",
    "boundary": "범위 경계",
    "sampleNodes": "표본 노드",
    "linkedBank": "연결된 Bank 기록",
    "scenarioVisualization": "시나리오 시각화",
    "constellation": "별자리",
    "graph": "그래프",
    "table": "표",
    "timeline": "시간선",
    "relationship": "관계",
    "sourceNode": "출처 노드",
    "targetNode": "대상 노드",
    "unknownTime": "시간 미상",
    "scenarioDetails": "시나리오 상세",
    "stable": "안정",
    "verified": "검증됨",
    "candidate": "후보",
    "unknown": "알 수 없음",
    "watch": "확인 필요",
    "revalidation": "재검증 대기",
    "deprecated": "사용 중단",
    "configured": "설정됨"
  },
  "zh-TW": {
    "localModelDirectory": "本機模型目錄",
    "dimensions": "向量維度",
    "device": "執行裝置",
    "embeddingProfiles": "Embedding 設定檔",
    "rerankerProfiles": "Rerank 設定檔",
    "copy": "複製",
    "enable": "啟用",
    "disable": "關閉",
    "source": "來源",
    "hostedUrl": "線上 API 網址",
    "fixedUrl": "固定服務網址",
    "fixedModel": "固定模型",
    "previousConfig": "原設定",
    "discovered": "發現",
    "modelId": "模型 ID",
    "providerName": "提供者名稱",
    "primaryProvider": "主要提供者",
    "remove": "移除",
    "unconfigured": "未設定",
    "scenarioHint": "Session/Project 情境摘要、複核狀態與圖譜涵蓋範圍。",
    "pendingReview": "待複核：",
    "qualityStatus": "品質狀態：",
    "graphNodes": "圖譜節點",
    "relationEdges": "· 關係邊",
    "timelineSuffix": "· 時間軸",
    "tier": "層級",
    "overview": "概覽",
    "standardSummary": "標準摘要",
    "fullSummary": "詳細摘要",
    "nodeName": "節點名稱",
    "scopeReview": "範圍複核",
    "sourceCount": "來源數",
    "sourceLocator": "來源定位",
    "none": "無",
    "boundary": "邊界",
    "sampleNodes": "圖譜樣本節點",
    "linkedBank": "Bank 已關聯",
    "scenarioVisualization": "情境摘要視覺化",
    "constellation": "星座",
    "graph": "圖譜",
    "table": "表格",
    "timeline": "時間軸",
    "relationship": "關係",
    "sourceNode": "來源節點",
    "targetNode": "目標節點",
    "unknownTime": "未知時間",
    "scenarioDetails": "情境摘要詳情",
    "stable": "穩定",
    "verified": "已驗證",
    "candidate": "候選",
    "unknown": "未知",
    "watch": "需關注",
    "revalidation": "待再驗證",
    "deprecated": "已棄用",
    "configured": "已設定"
  },
  "yue-Hant": {
    "localModelDirectory": "本機模型目錄",
    "dimensions": "向量維度",
    "device": "執行裝置",
    "embeddingProfiles": "Embedding 設定檔",
    "rerankerProfiles": "Rerank 設定檔",
    "copy": "複製",
    "enable": "啟用",
    "disable": "關閉",
    "source": "來源",
    "hostedUrl": "線上 API 網址",
    "fixedUrl": "固定服務網址",
    "fixedModel": "固定模型",
    "previousConfig": "原有設定",
    "discovered": "發現",
    "modelId": "模型 ID",
    "providerName": "提供者名稱",
    "primaryProvider": "主要提供者",
    "remove": "移除",
    "unconfigured": "未設定",
    "scenarioHint": "Session/Project 情境摘要、覆核狀態同圖譜涵蓋範圍。",
    "pendingReview": "待覆核：",
    "qualityStatus": "品質狀態：",
    "graphNodes": "圖譜節點",
    "relationEdges": "· 關係邊",
    "timelineSuffix": "· 時間線",
    "tier": "層級",
    "overview": "概覽",
    "standardSummary": "標準摘要",
    "fullSummary": "詳細摘要",
    "nodeName": "節點名稱",
    "scopeReview": "範圍覆核",
    "sourceCount": "來源數目",
    "sourceLocator": "來源定位",
    "none": "無",
    "boundary": "邊界",
    "sampleNodes": "圖譜樣本節點",
    "linkedBank": "Bank 已關聯",
    "scenarioVisualization": "情境摘要視覺化",
    "constellation": "星座",
    "graph": "圖譜",
    "table": "表格",
    "timeline": "時間線",
    "relationship": "關係",
    "sourceNode": "來源節點",
    "targetNode": "目標節點",
    "unknownTime": "未知時間",
    "scenarioDetails": "情境摘要詳情",
    "stable": "穩定",
    "verified": "已驗證",
    "candidate": "候選",
    "unknown": "未知",
    "watch": "需要留意",
    "revalidation": "待再驗證",
    "deprecated": "已棄用",
    "configured": "已設定"
  }
};
