// Semantic labels for legacy call sites. Other locales explicitly fall back to English.
export const RELEASE_UI_COPY: Record<string, { source: string; en: string }> = {
"hostReplayScope": {source:"同一 Prompt / 宿主原始工具结果回放（不代表回答采用）",en:"Same Prompt / retained host tool results (does not imply answer adoption)"},
"selectedProfileHint": { source: "档案已选择，保存后应用；身份变化需要重建索引", en: "Profile selected; save to apply. Identity changes require index rebuilding." },
"runtimeIntro": { source: "查看当前实际使用的模型、宿主和本机服务。版本", en: "Models, host and local services currently in use. Version" },
"tier": { source: "层级", en: "Tier" },
"scannedSamplePrefix": { source: "条扫描记录（页面样本", en: "scanned records (visible sample:" },
"scannedSampleSuffix": { source: "条）", en: "items)" },
"loadingConfig": { source: "正在读取配置…", en: "Loading configuration…" },
"record": { source: "记录", en: "Record" },
"retrieve": { source: "检索", en: "Retrieve" },
"recordingDisabled": { source: "已关闭记录：不会产生新的该类过程记忆，已有数据不会删除。", en: "Recording is disabled; existing process records are retained." },
"userModules": { source: "事实、经历、实体、偏好、情景摘要和原文回读的运行开关。", en: "Controls for facts, experiences, entities, preferences, scenarios and source readback." },
"backupSaveFailed": { source: "备份设置保存失败", en: "Backup settings could not be saved" },
"backupSaved": { source: "备份设置已保存并应用", en: "Backup settings saved and applied" },
"chooseDirectoryHint": { source: "点击按钮选择目录", en: "Choose a directory with the button" },
"embeddingBinding": { source: "绑定 Embedding 配置", en: "Embedding profile binding" },
"rerankerBinding": { source: "绑定 Rerank 配置", en: "Rerank profile binding" },
"rerankerUnavailable": { source: "当前 Re-rank 开关已打开，但未启用可加载的 Rerank 模型；实际检索会回退为候选顺序，建议先到“检索与判断模型”启用并验证模型。", en: "Rerank is requested but no loadable model is enabled. Retrieval uses candidate order until a model is enabled and verified." },
"ragIndexCompatibility": { source: "RAG 会按上面的绑定读取检索与判断模型；更换 Embedding 后需重建外部索引，避免旧向量与新维度混用。", en: "RAG uses the bound profiles. Changing the embedding model requires rebuilding the index, even when dimensions match." },
"modelsSaved": { source: "检索与判断模型配置已保存", en: "Retrieval and judge settings saved" },
"modelsHint": { source: "统一管理 Embedding、Rerank、融合算法，以及可选的 JEV 判断服务。", en: "Configure embedding, reranking, fusion and optional JEV judgment." },
"embeddingProfiles": { source: "Embedding 配置档案", en: "Embedding profiles" },
"rerankerProfiles": { source: "Rerank 配置档案", en: "Rerank profiles" },
"copy": { source: "复制", en: "Copy" },
"profileHint": { source: "档案保存后可在外部 RAG 页面选择；更换 Embedding 会触发索引重建提示。", en: "Saved profiles are available to RAG. Changing embedding identity requires index rebuilding." },
"rrfHint": { source: "RRF 是候选融合算法，不是 Rerank 模型。", en: "RRF fuses candidates; reranking requires a separate model." },
"enable": { source: "启用", en: "Enable" },
"disable": { source: "关闭", en: "Off" },
"fixedUrl": { source: "固定服务地址", en: "Managed service URL" },
"fixedModel": { source: "固定模型", en: "Managed model" },
"managedModelHint": { source: "地址和模型由 EP 固定管理，无需填写。", en: "EP manages the URL and model." },
"keepSavedKey": { source: "留空表示保留已保存密钥", en: "Leave blank to keep the saved key" },
"fallbackChain": { source: "规则脚本 → 本地模型（如已启用） → 保守未知", en: "Rules → local model if enabled → unknown" },
"source": { source: "来源", en: "Source" },
"localModelDirectory": { source: "本地模型目录", en: "Local model directory" },
"dimensions": { source: "向量维度", en: "Vector dimensions" },
"device": { source: "运行设备", en: "Device" },
"hostedUrl": { source: "线上 API 地址", en: "Hosted API URL" },
"localMatch": { source: "已自动匹配本地目录", en: "Local directory discovered" },
"dimensionMatchLegacy": { source: "已按维度自动匹配本地模型", en: "Legacy dimension-based match requires identity review" },
"modelMissing": { source: "未找到当前模型的本地目录", en: "Local directory for the configured model is missing" },
"localModelStatus": { source: "本地模型状态", en: "Local model status" },
"previousConfig": { source: "原配置", en: "Previous configuration" },
"applyMatched": { source: "保存后将使用上方已匹配模型", en: "Review model identity before applying this proposal" },
"discoveryHint": { source: "系统已扫描本机模型目录；请从下方真实候选中选择，不会把不同模型静默当成同一个模型。", en: "Discovered files are proposals. Matching dimensions do not prove model or index compatibility." },
"discovered": { source: "发现", en: "Discovered" },
"maskedKeyError": { source: "连接测试失败：页面中的掩码密钥不能直接发送，请重新输入真实 API Key。", en: "Masked keys cannot be used for connection tests. Enter the actual key." },
"providerConnectionError": { source: "连接测试失败：无法连接到 Provider，请检查地址、代理服务和端口。", en: "Could not connect to the provider. Check its URL, proxy and port." },
"requestFailed": { source: "连接测试失败：请求未完成，请稍后重试。", en: "The connection test did not complete. Try again later." },
"unconfigured": { source: "未配置", en: "Not configured" },
"testFailed": { source: "连接测试失败，请检查配置后重试。", en: "Connection test failed. Check the configuration." },
"providerSaved": { source: "Provider 配置已保存", en: "Provider configuration saved" },
"providerHint": { source: "主 Provider 失败时按顺序切换备用 Provider；API Key 只显示掩码。", en: "Fallback providers run in order when the primary fails. Keys are masked." },
"primaryProvider": { source: "主 Provider", en: "Primary provider" },
"remove": { source: "移除", en: "Remove" },
"providerName": { source: "提供商名称", en: "Provider name" },
"modelId": { source: "模型 ID", en: "Model ID" },
"keepOriginalKey": { source: "留空表示保留原 Key", en: "Leave blank to keep the original key" },
"providerTestHint": { source: "连接测试只访问 Provider 的模型列表接口，不会发送 EP 记忆内容。", en: "The test requests the model list without sending memory contents." },
"scenarioHint": { source: "Session/Project 情境摘要、复核状态和图谱读取状态。", en: "Session and project summaries, review status and graph coverage." },
"pendingReview": { source: "待复核：", en: "Pending review:" },
"qualityStatus": { source: "质量状态：", en: "Quality status:" },
"graphNodes": { source: "图谱节点", en: "Graph nodes" },
"relationEdges": { source: "· 关系边", en: "· relationship edges" },
"timelineSuffix": { source: "· 时间线", en: "· timeline" },
"backup": { source: "备份", en: "Backup" },
"backupHint": { source: "分别设置执行计划、保留期限和自动清理规则。", en: "Set backup schedules, retention limits and cleanup rules." },
"schedule": { source: "执行计划", en: "Schedule" },
"scheduleMode": { source: "执行方式", en: "Schedule mode" },
"daily": { source: "每天", en: "Daily" },
"weekly": { source: "每周", en: "Weekly" },
"monthly": { source: "每月", en: "Monthly" },
"intervalDays": { source: "每隔指定天数", en: "Every specified number of days" },
"interval": { source: "间隔天数", en: "Interval in days" },
"hours": { source: "小时", en: "Hours" },
"minutes": { source: "分钟", en: "Minutes" },
"localRetention": { source: "本地保留策略", en: "Local retention" },
"maxDays": { source: "最长保留天数", en: "Maximum retention days" },
"maxSets": { source: "最多保留套数", en: "Maximum backup sets" },
"minSuccessSets": { source: "至少保留成功备份套数", en: "Minimum successful backup sets" },
"cleanupOldest": { source: "超过期限或数量后自动清理最旧备份", en: "Clean up oldest backups when limits are exceeded" },
"cloudRetention": { source: "云端保留", en: "Cloud retention" },
"maxCloudSets": { source: "最多保留云端套数", en: "Maximum cloud backup sets" },
"cloudMirror": { source: "启用云端镜像", en: "Enable cloud mirror" },
"saveBackup": { source: "保存备份设置", en: "Save backup settings" },
"containsSession": { source: "包含会话", en: "Contains session" },
"sameDirectorySession": { source: "同目录会话", en: "Session in the same directory" },
"associatedRecord": { source: "关联记录", en: "Associated record" },
"sameDirectoryRecord": { source: "同目录记录", en: "Record in the same directory" },
"sourceSession": { source: "来源会话", en: "Source session" },
"verifiedProject": { source: "已核实 Project", en: "Verified project" },
"workspaceClue": { source: "工作目录线索", en: "Workspace clue" },
"sessionContext": { source: "Session 情境", en: "Session context" },
"bankFact": { source: "Bank 事实", en: "Bank fact" },
"bankExperience": { source: "Bank 经历", en: "Bank experience" },
"bankRecord": { source: "Bank 记录", en: "Bank record" },
"noSummary": { source: "当前节点没有可显示的摘要。", en: "No summary is available for this node." },
"workspaceBoundary": { source: "这只是相同工作目录的会话集合，不能据此认定为同一个项目。", en: "Sharing a workspace does not establish a shared project." },
"unreviewedProjection": { source: "确定性来源投影，尚未完成语义复核。", en: "Source projection is available; semantic review is pending." },
"reviewBoundary": { source: "已按会话原文复核摘要；文件、发送和外部事实未在此核验。", en: "Summary reviewed against session text; files, delivery and external facts are unverified." },
"overview": { source: "概览", en: "Overview" },
"standardSummary": { source: "标准摘要", en: "Standard summary" },
"fullSummary": { source: "详细摘要", en: "Detailed summary" },
"truncated": { source: " · 已截断", en: " · truncated" },
"nodeName": { source: "节点名称", en: "Node name" },
"scopeReview": { source: "范围复核", en: "Scope review" },
"unrecorded": { source: "未记录", en: "Not recorded" },
"sourceCount": { source: "来源数", en: "Source count" },
"sourceLocator": { source: "来源定位", en: "Source locator" },
"none": { source: "无", en: "None" },
"boundary": { source: "边界", en: "Boundary" },
"sourceLocatorBoundary": { source: "来源定位是本机摘要路径，不是 Bank 的 read_source ID；关键事实仍需回到原始证据核验。", en: "This locator identifies a local summary, not a Bank read_source ID. Verify key facts against original evidence." },
"noScenarioIndex": { source: "当前 Bank 尚未建立独立的情景摘要索引。", en: "This Bank has no independent scenario index." },
"workspaceCandidateCount": { source: "工作目录候选 · 非项目数", en: "Workspace candidates · not project count" },
"sampleNodes": { source: "图谱样本节点", en: "Sampled graph nodes" },
"linkedBank": { source: "Bank 已关联", en: "Linked Bank records" },
"scenarioVisualization": { source: "情景摘要可视化", en: "Scenario visualization" },
"scenarioViewsHint": { source: "与事实、经历、实体页使用同一套星座图、图谱、表格、时间线视图；点击节点可查看详情。", en: "Explore constellation, graph, table and timeline views. Select a node for details." },
"purpleWorkspace": { source: "紫：工作目录线索", en: "Purple: workspace clues" },
"greenSession": { source: "绿：Session", en: "Green: sessions" },
"blueBank": { source: "蓝：Bank 记录", en: "Blue: Bank records" },
"constellation": { source: "星座", en: "Constellation" },
"graph": { source: "图谱", en: "Graph" },
"table": { source: "表格", en: "Table" },
"timeline": { source: "时间线", en: "Timeline" },
"relationship": { source: "关系", en: "Relationship" },
"sourceNode": { source: "来源节点", en: "Source node" },
"targetNode": { source: "目标节点", en: "Target node" },
"viewSourceNode": { source: "查看来源节点", en: "View source node" },
"viewTargetNode": { source: "查看目标节点", en: "View target node" },
"unknownTime": { source: "未知时间", en: "Unknown time" },
"scenarioDetails": { source: "情境摘要详情", en: "Scenario summary details" },
"constellationHelp": { source: "星座图说明", en: "Constellation guide" },
"graphHelp": { source: "图谱说明", en: "Graph guide" },
"tableHelp": { source: "关系表说明", en: "Relationship table guide" },
"timelineHelp": { source: "时间线说明", en: "Timeline guide" },
"selectNodeHint": { source: "点击图谱节点、表格中的来源或目标节点、时间线项目，详情显示在此处。", en: "Select a graph node, table endpoint or timeline item to inspect details here." },
"scenarioColors": { source: "紫色是 Project，绿色是 Session，蓝色是 Bank 事实/经历/记录。", en: "Purple: projects; green: sessions; blue: Bank records." },
"graphDisplays": { source: "当前图谱展示", en: "Graph displays" },
"sampleTotal": { source: "个样本节点，共", en: "sampled nodes; total" },
"bankLinksSuffix": { source: "条 Bank 关联。", en: "Bank links." },
"bankSnapshot": { source: "Bank 关联快照：", en: "Bank association snapshot:" },
"noSnapshot": { source: "尚无可用关联快照", en: "No association snapshot available" },
"bankTotalPrefix": { source: "。当前 Bank 共", en: ". Bank total:" },
"newSinceSnapshot": { source: "条，快照后新增", en: "records; added since snapshot:" },
"unscannedSince": { source: "条未扫描；快照时间", en: "unscanned records; snapshot time:" },
"scenarioReviewSuffix": { source: "；情景摘要待复核", en: "; scenario summaries awaiting review:" },
"itemsSuffix": { source: "条。", en: "items." },
"publishedQueue": { source: "已发布版本可用 · 新增资料排队整理", en: "Published version available · new material queued" },
"contextDelivery": { source: "上下文送达", en: "Context delivery" },
"occurrenceTotals": { source: "累计扫描/返回可重复；去重来源", en: "Scan and return totals may overlap; unique sources" },
"identityDrift": { source: "模型档案身份不一致", en: "Model profile identity mismatch" },
"signatureUnknown": { source: "索引签名与服务加载状态未核验", en: "Index signature and service loading are unverified" },
"discoveryProposal": { source: "发现建议；尚未应用", en: "Discovery proposal; not applied" },
"configured": { source: "已配置", en: "Configured" },
"stable": { source: "稳定", en: "Stable" },
"verified": { source: "已验证", en: "Verified" },
"candidate": { source: "候选", en: "Candidate" },
"unknown": { source: "未知", en: "Unknown" },
"watch": { source: "需关注", en: "Needs attention" },
"revalidation": { source: "待再验证", en: "Revalidation pending" },
"deprecated": { source: "已弃用", en: "Deprecated" },
"understand": { source: "理解", en: "Understand" },
"plan": { source: "规划", en: "Plan" },
"act": { source: "执行", en: "Act" },
"observe": { source: "观察", en: "Observe" },
"recover": { source: "恢复", en: "Recover" },
"deliver": { source: "交付", en: "Deliver" },
"reflect": { source: "反思", en: "Reflect" },
};
